import { Graph } from './Graph';
import { Point } from './Point';
import { Cardinality, RelationshipType } from './Relationship';

export interface Theme {
  name: string;
  description: string;
  graph: Graph;
}

export const themes: Theme[] = [
  {
    name: 'Chunky',
    description: 'For simple, bold diagrams.',
    graph: {
      description: '',
      nodes: [
        {
          id: 'n0',
          entityType: 'node',
          position: new Point(-52, 0),
          // {
          //   "x": -52,
          //   "y": 0
          // },
          caption: 'a',
          style: {},
          properties: {},
          description: '',
        },
        {
          id: 'n1',
          entityType: 'node',
          position: new Point(309.5734899055742, 0),
          // {
          //   "x": 309.5734899055742,
          //   "y": 0
          // },
          caption: 'b',
          style: {},
          properties: {},
          description: '',
        },
      ],
      relationships: [
        {
          id: 'n0',
          entityType: 'relationship',
          type: 'KNOWS',
          style: {},
          properties: {},
          fromId: 'n0',
          toId: 'n1',
          relationshipType: RelationshipType.ASSOCIATION,
          cardinality: Cardinality.ONE_TO_MANY,
          description: '',
        },
      ],
      style: {
        'font-family': 'sans-serif',
        'background-color': '#ffffff',
        'class-color': '#ffffff',
        'border-width': 4,
        'border-color': '#000000',
        radius: 50,
        'class-padding': 5,
        'outside-position': 'auto',
        'class-icon-image': '',
        'class-background-image': '',
        'icon-position': 'inside',
        'icon-size': 64,
        'class-name-position': 'inside',
        'class-name-max-width': 200,
        'class-name-color': '#000000',
        'class-name-font-size': 50,
        'class-name-font-weight': 'normal',
        'label-position': 'inside',
        'label-display': 'pill',
        'label-color': '#000000',
        'label-background-color': '#ffffff',
        'label-border-color': '#000000',
        'label-border-width': 4,
        'label-font-size': 40,
        'label-padding': 5,
        'label-margin': 4,
        'detail-position': 'inline',
        'detail-orientation': 'parallel',
        'arrow-width': 5,
        'arrow-color': '#000000',
        'margin-start': 5,
        'margin-end': 5,
        'margin-peer': 20,
        'attachment-start': 'normal',
        'attachment-end': 'normal',
        'relationship-icon-image': '',
        'type-color': '#000000',
        'type-background-color': '#ffffff',
        'type-border-color': '#000000',
        'type-border-width': 0,
        'type-font-size': 16,
        'type-padding': 5,
        'attribute-position': 'outside',
        'attribute-color': '#000000',
        'attribute-font-size': 16,
        'attribute-font-weight': 'normal',
      },
    },
  },
  {
    name: 'Dark Code',
    description: 'Light-on-dark contrast similar to an IDE',
    graph: {
      description: '',
      style: {
        'font-family': 'Fira Code',
        'background-color': '#2B2B2B',
        'class-color': '#2B2B2B',
        'border-width': 2,
        'border-color': '#A6B7C8',
        radius: 90,
        'class-padding': 5,
        'class-margin': 2,
        'outside-position': 'auto',
        'class-icon-image': '',
        'class-background-image': '',
        'icon-position': 'inside',
        'icon-size': 64,
        'class-name-position': 'inside',
        'class-name-max-width': 200,
        'class-name-color': '#A6B7C8',
        'class-name-font-size': 18,
        'class-name-font-weight': 'normal',
        'label-position': 'inside',
        'label-display': 'bare',
        'label-color': '#A6B7C8',
        'label-background-color': '#ffffff',
        'label-border-color': '#000000',
        'label-border-width': 4,
        'label-font-size': 18,
        'label-padding': 5,
        'label-margin': 4,
        'detail-position': 'inline',
        'detail-orientation': 'parallel',
        'arrow-width': 2,
        'arrow-color': '#A6B7C8',
        'margin-start': 0,
        'margin-end': 0,
        'margin-peer': 20,
        'attachment-start': 'normal',
        'attachment-end': 'normal',
        'relationship-icon-image': '',
        'type-color': '#A6B7C8',
        'type-background-color': '#2B2B2B',
        'type-border-color': '#000000',
        'type-border-width': 0,
        'type-font-size': 18,
        'type-padding': 5,
        'attribute-position': 'inside',
        'attribute-alignment': 'colon',
        'attribute-color': '#A6B7C8',
        'attribute-font-size': 18,
        'attribute-font-weight': 'normal',
      },
      nodes: [
        {
          id: 'n0',
          entityType: 'node',
          position: new Point(11.499999999999986, -74.54584527220625),
          // {
          //   "x": 11.499999999999986,
          //   "y": -74.54584527220625
          // },
          caption: '',
          properties: {
            SKU: { description: '750045', multivalued: false },
            unit: { description: '100', multivalued: false },
          },
          style: {},
          description: '',
        },
        {
          id: 'n1',
          entityType: 'node',
          position: new Point(381.4169054441258, -74.54584527220625),
          // {
          //   "x": 381.4169054441258,
          //   "y": -74.54584527220625
          // },
          caption: '',
          properties: {
            stock: { description: 'true', multivalued: false },
          },
          style: {},
          description: '',
        },
      ],
      relationships: [
        {
          id: 'n0',
          entityType: 'relationship',
          type: 'CATEGORY',
          style: {},
          properties: {},
          fromId: 'n0',
          toId: 'n1',
          relationshipType: RelationshipType.ASSOCIATION,
          cardinality: Cardinality.ONE_TO_MANY,
          description: '',
        },
      ],
    },
  },
  {
    name: 'Bloom',
    description: 'Theme based on Neo4j Bloom.',
    graph: {
      description: '',
      style: {
        'font-family': 'Nunito Sans',
        'background-color': '#F2F2F2',
        'class-color': '#4C8EDA',
        'border-width': 0,
        'border-color': '#000000',
        radius: 75,
        'class-padding': 5,
        'outside-position': 'auto',
        'class-icon-image': '',
        'class-background-image': '',
        'icon-position': 'inside',
        'icon-size': 64,
        'class-name-position': 'inside',
        'class-name-max-width': 200,
        'class-name-color': '#ffffff',
        'class-name-font-size': 20,
        'class-name-font-weight': 'normal',
        'label-position': 'inside',
        'label-display': 'bare',
        'label-color': '#ffffff',
        'label-background-color': '#848484',
        'label-border-color': '#848484',
        'label-border-width': 3,
        'label-font-size': 20,
        'label-padding': 5,
        'label-margin': 4,
        'detail-position': 'above',
        'detail-orientation': 'parallel',
        'arrow-width': 3,
        'arrow-color': '#848484',
        'margin-start': 5,
        'margin-end': 5,
        'margin-peer': 20,
        'attachment-start': 'normal',
        'attachment-end': 'normal',
        'relationship-icon-image': '',
        'type-color': '#848484',
        'type-background-color': '#F2F2F2',
        'type-border-color': '#848484',
        'type-border-width': 0,
        'type-font-size': 21,
        'type-padding': 5,
        'attribute-position': 'outside',
        'attribute-color': '#848484',
        'attribute-font-size': 20,
        'attribute-font-weight': 'normal',
      },
      nodes: [
        {
          id: 'n0',
          entityType: 'node',
          position: new Point(-108, 0),
          // {
          //   "x": -108,
          //   "y": 0
          // },
          caption: 'Liv Tyler',
          style: {
            'class-color': '#F79767',
          },
          properties: {},
          description: '',
        },
        {
          id: 'n1',
          entityType: 'node',
          position: new Point(309.5734899055742, 0),
          // {
          //   "x": 309.5734899055742,
          //   "y": 0
          // },
          caption: 'That thing you do',
          style: {},
          properties: {},
          description: '',
        },
      ],
      relationships: [
        {
          id: 'n0',
          entityType: 'relationship',
          type: 'ACTED IN',
          style: {},
          properties: {},
          fromId: 'n0',
          toId: 'n1',
          relationshipType: RelationshipType.ASSOCIATION,
          cardinality: Cardinality.ONE_TO_MANY,
          description: '',
        },
      ],
    },
  },
  {
    name: 'Browser',
    description: 'Theme based on Neo4j Browser',
    graph: {
      description: '',
      style: {
        'font-family': 'sans-serif',
        'background-color': '#FAFCFF',
        'class-color': '#4C8EDA',
        'border-width': 2,
        'border-color': '#2870c2',
        radius: 25,
        'class-padding': 5,
        'outside-position': 'auto',
        'class-icon-image': '',
        'class-background-image': '',
        'icon-position': 'inside',
        'icon-size': 64,
        'class-name-position': 'inside',
        'class-name-max-width': 200,
        'class-name-color': '#ffffff',
        'class-name-font-size': 10,
        'class-name-font-weight': 'normal',
        'label-position': 'outside',
        'label-display': 'bare',
        'label-color': '#ffffff',
        'label-background-color': '#4C8EDA',
        'label-border-color': '#4C8EDA',
        'label-border-width': 0,
        'label-font-size': 10,
        'label-padding': 2,
        'label-margin': 2,
        'detail-position': 'inline',
        'detail-orientation': 'parallel',
        'arrow-width': 1,
        'arrow-color': '#A5ABB6',
        'margin-start': 0,
        'margin-end': 0,
        'margin-peer': 20,
        'attachment-start': 'normal',
        'attachment-end': 'normal',
        'relationship-icon-image': '',
        'type-color': '#000000',
        'type-background-color': '#ffffff',
        'type-border-color': '#000000',
        'type-border-width': 0,
        'type-font-size': 10,
        'type-padding': 2,
        'attribute-position': 'outside',
        'attribute-color': '#000000',
        'attribute-font-size': 10,
        'attribute-font-weight': 'normal',
      },
      nodes: [
        {
          id: 'n0',
          entityType: 'node',
          position: new Point(3.8854047888817544, 0),
          // {
          //   "x": 3.8854047888817544,
          //   "y": 0
          // },
          caption: 'Tom Hanks',
          style: {
            'class-color': '#F79767',
            'border-color': '#f36924',
          },
          description: '',
          properties: {},
        },
        {
          id: 'n1',
          entityType: 'node',
          position: new Point(144.87486013982567, 0),
          // {
          //   "x": 144.87486013982567,
          //   "y": 0
          // },
          caption: 'The Da Vinci Code',
          style: {},
          properties: {
            released: { description: '2006', multivalued: false },
            tagline: { description: 'Break The Codes', multivalued: false },
            title: { description: 'The Da Vinci Code', multivalued: false },
          },
          description: '',
        },
      ],
      relationships: [
        {
          id: 'n0',
          entityType: 'relationship',
          type: 'ACTED_IN',
          style: {},
          properties: {},
          fromId: 'n0',
          toId: 'n1',
          relationshipType: RelationshipType.ASSOCIATION,
          description: '',
          cardinality: Cardinality.ONE_TO_MANY,
        },
      ],
    },
  },
  {
    name: 'Iconic',
    description: 'Minimal undirected graphs suitable for very small pictures',
    graph: {
      description: '',
      style: {
        'font-family': 'sans-serif',
        'background-color': '#ffffff',
        'class-color': '#ffffff',
        'border-width': 2,
        'border-color': '#000000',
        radius: 10,
        'class-padding': 5,
        'outside-position': 'auto',
        'class-icon-image': '',
        'class-background-image': '',
        'icon-position': 'inside',
        'icon-size': 64,
        'class-name-position': 'outside',
        'class-name-max-width': 200,
        'class-name-color': '#000000',
        'class-name-font-size': 10,
        'class-name-font-weight': 'normal',
        'label-position': 'outside',
        'label-display': 'pill',
        'label-color': '#000000',
        'label-background-color': '#ffffff',
        'label-border-color': '#000000',
        'label-border-width': 2,
        'label-font-size': 10,
        'label-padding': 1,
        'label-margin': 4,
        'detail-position': 'inline',
        'detail-orientation': 'parallel',
        'arrow-width': 2,
        'arrow-color': '#000000',
        'margin-start': 0,
        'margin-end': 0,
        'margin-peer': 20,
        'attachment-start': 'normal',
        'attachment-end': 'normal',
        'relationship-icon-image': '',
        'type-color': '#000000',
        'type-background-color': '#ffffff',
        'type-border-color': '#000000',
        'type-border-width': 0,
        'type-font-size': 10,
        'type-padding': 5,
        'attribute-position': 'outside',
        'attribute-color': '#000000',
        'attribute-font-size': 10,
        'attribute-font-weight': 'normal',
      },
      nodes: [
        {
          id: 'n0',
          entityType: 'node',
          position: new Point(-16.5, 0),
          // {
          //   "x": -16.5,
          //   "y": 0
          // },
          caption: '',
          style: {
            'class-color': '#7b64ff',
          },
          description: '',
          properties: {},
        },
        {
          id: 'n1',
          entityType: 'node',
          position: new Point(-39.78102752569192, 40.6310118348138),
          // {
          //   "x": -39.78102752569192,
          //   "y": 40.6310118348138
          // },
          caption: '',
          style: {},
          description: '',
          properties: {},
        },
        {
          id: 'n2',
          entityType: 'node',
          position: new Point(6.781027525691918, 40.6310118348138),
          // {
          //   "x": 6.781027525691918,
          //   "y": 40.6310118348138
          // },
          caption: '',
          style: {},
          description: '',
          properties: {},
        },
        {
          id: 'n3',
          entityType: 'node',
          position: new Point(-39.78102752569192, -40.631011834813805),
          // {
          //   "x": -39.78102752569192,
          //   "y": -40.631011834813805
          // },
          caption: '',
          style: {
            'class-color': '#fcdc00',
          },
          description: '',
          properties: {},
        },
        {
          id: 'n4',
          entityType: 'node',
          position: new Point(-63.32825392188784, 0),
          // {
          //   "x": -63.32825392188784,
          //   "y": 0
          // },
          caption: '',
          style: {},
          description: '',
          properties: {},
        },
        {
          id: 'n5',
          entityType: 'node',
          position: new Point(30.328253921887843, 0),
          // {
          //   "x": 30.328253921887843,
          //   "y": 0
          // },
          caption: '',
          style: {},
          description: '',
          properties: {},
        },
        {
          id: 'n6',
          entityType: 'node',
          position: new Point(6.781027525691918, -40.631011834813805),
          // {
          //   "x": 6.781027525691918,
          //   "y": -40.631011834813805
          // },
          caption: '',
          style: {},
          description: '',
          properties: {},
        },
        {
          id: 'n7',
          entityType: 'node',
          position: new Point(53.609281447579775, 40.6310118348138),
          // {
          //   "x": 53.609281447579775,
          //   "y": 40.6310118348138
          // },
          caption: '',
          style: {
            'class-color': '#c45100',
          },
          description: '',
          properties: {},
        },
      ],
      relationships: [
        {
          id: 'n0',
          entityType: 'relationship',
          type: '',
          style: {},
          properties: {},
          fromId: 'n0',
          toId: 'n1',
          relationshipType: RelationshipType.ASSOCIATION,
          description: '',
          cardinality: Cardinality.ONE_TO_MANY,
        },
        {
          id: 'n1',
          entityType: 'relationship',
          type: '',
          style: {},
          properties: {},
          fromId: 'n0',
          toId: 'n2',
          relationshipType: RelationshipType.ASSOCIATION,
          description: '',
          cardinality: Cardinality.ONE_TO_MANY,
        },
        {
          id: 'n2',
          entityType: 'relationship',
          type: '',
          style: {},
          properties: {},
          fromId: 'n1',
          toId: 'n2',
          relationshipType: RelationshipType.ASSOCIATION,
          description: '',
          cardinality: Cardinality.ONE_TO_MANY,
        },
        {
          id: 'n3',
          entityType: 'relationship',
          type: '',
          style: {},
          properties: {},
          fromId: 'n0',
          toId: 'n3',
          relationshipType: RelationshipType.ASSOCIATION,
          description: '',
          cardinality: Cardinality.ONE_TO_MANY,
        },
        {
          id: 'n4',
          entityType: 'relationship',
          type: '',
          style: {},
          properties: {},
          fromId: 'n0',
          toId: 'n4',
          relationshipType: RelationshipType.ASSOCIATION,
          description: '',
          cardinality: Cardinality.ONE_TO_MANY,
        },
        {
          id: 'n5',
          entityType: 'relationship',
          type: '',
          style: {},
          properties: {},
          fromId: 'n0',
          toId: 'n5',
          relationshipType: RelationshipType.ASSOCIATION,
          description: '',
          cardinality: Cardinality.ONE_TO_MANY,
        },
        {
          id: 'n6',
          entityType: 'relationship',
          type: '',
          style: {},
          properties: {},
          fromId: 'n0',
          toId: 'n6',
          relationshipType: RelationshipType.ASSOCIATION,
          description: '',
          cardinality: Cardinality.ONE_TO_MANY,
        },
        {
          id: 'n7',
          entityType: 'relationship',
          type: '',
          style: {},
          properties: {},
          fromId: 'n5',
          toId: 'n7',
          relationshipType: RelationshipType.ASSOCIATION,
          description: '',
          cardinality: Cardinality.ONE_TO_MANY,
        },
        {
          id: 'n8',
          entityType: 'relationship',
          type: '',
          style: {},
          properties: {},
          fromId: 'n4',
          toId: 'n1',
          relationshipType: RelationshipType.ASSOCIATION,
          description: '',
          cardinality: Cardinality.ONE_TO_MANY,
        },
      ],
    },
  },
];
